### ISSUE TITLE
Add license header to each source file

### ISSUE THREAD

**Issue by polsys** [polsys/ennemi#47]
This is a good practice.

**Comment by morrme** [comment]
Do you want this on all of the /benchmarks/ files in addition to the /ennemi/ files?

**Comment by polsys** [comment]
Hi!
I think it would be good to have the header in all of `benchmarks`, `ennemi` and `tests` plus `setup.py`. Maybe something like
```python
# MIT License - Copyright Petri Laarne and contributors
# See the LICENSE.md file included in this source code package
```

**Comment by morrme** [comment]
So you do not want the full license header anywhere? Just a reference to the file?

**Comment by polsys** [comment]
Yes, I think it would be enough. As far as I understand, the MIT license does not require even the header, but it's considered a good practice. Having the full license text in every file would be distracting, I think. Please correct me if I'm wrong :)

**Comment by morrme** [comment]
correct; it is not required but nice to do. I've seen it formatted both ways, so what you've chosen is totally fine :)
